import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../../../core/theme/colors";

const { width } = Dimensions.get("window");

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  channelSelector: {
    marginTop: 10,
    paddingHorizontal: 10,
  },
  channelButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginRight: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  channelButtonActive: {
    backgroundColor: COLORS.light.primary,
    borderColor: COLORS.light.primary,
  },
  channelButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  channelButtonTextActive: {
    color: "#fff",
    fontWeight: "bold",
  },
  tvFrame: {
    width: width - 20,
    height: 220,
    backgroundColor: "#000",
    borderRadius: 10,
    overflow: "hidden",
    marginTop: 0,
    marginHorizontal: 10,
    elevation: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
  },
  tvImage: {
    width: "100%",
    height: "100%",
  },
  noStreamContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  noStreamText: {
    color: "#fff",
    fontSize: 16,
  },
  infoSection: {
    marginTop: 10,
    paddingHorizontal: 20,
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "left",
  },
  subtitle: {
    fontSize: 14,
    color: "#e0e0e0",
    marginTop: 8,
    textAlign: "left",
    lineHeight: 22,
  },
  myChannelBtn: {
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 15,
    backgroundColor: COLORS.light.primary,
    borderRadius: 20,
  },
  myChannelText: {
    color: "#fff",
    fontWeight: "bold",
  },
  controls: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    width: width - 1,
    marginTop: 20,
    backgroundColor: "rgba(255,255,255,0.1)",
    // borderRadius: 30,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  liveBadge: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "#ff4757",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
  },
  liveText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 12,
  },
  tabBar: {
    marginTop: 30,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  tabButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginRight: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  tabButtonActive: {
    backgroundColor: COLORS.light.primary,
    borderColor: COLORS.light.primary,
  },
  tabButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
  },
  tabButtonTextActive: {
    color: "#fff",
    fontWeight: "bold",
  },
  sectionTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    marginLeft: 20,
    marginBottom: 15,
    marginTop: 10,
  },
  programCard: {
    width: 140,
    marginLeft: 20,
    marginRight: 10,
    backgroundColor: "#1e1e1e",
    borderRadius: 15,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  programTitle: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "bold",
  },
  programDate: {
    color: "#e0e0e0",
    fontSize: 12,
    marginTop: 5,
  },
  podcastCard: {
    width: 140,
    marginLeft: 20,
    marginRight: 10,
    backgroundColor: "#1e1e1e",
    borderRadius: 15,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  podcastText: {
    color: "#fff",
    fontSize: 14,
    marginLeft: 10,
  },
  videoCard: {
    width: 140,
    marginLeft: 20,
    marginRight: 10,
    backgroundColor: "#1e1e1e",
    borderRadius: 15,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  videoThumbnail: {
    width: "100%",
    height: 100,
    backgroundColor: "#333",
  },
  videoTitle: {
    color: "#fff",
    fontSize: 14,
    marginTop: 8,
    marginBottom: 10,
    textAlign: "center",
    paddingHorizontal: 5,
    fontWeight: "500",
  },
  eventItem: {
    marginHorizontal: 20,
    marginBottom: 15,
    backgroundColor: "#1e1e1e",
    borderRadius: 15,
    padding: 15,
    borderWidth: 1,
    borderColor: "#333",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  eventTitle: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  eventDate: {
    color: "#e0e0e0",
    fontSize: 14,
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: width - 40,
    backgroundColor: "#1e1e1e",
    borderRadius: 20,
    padding: 20,
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  input: {
    backgroundColor: "#333",
    color: "#fff",
    padding: 10,
    borderRadius: 10,
    marginBottom: 10,
  },
  addBtn: {
    backgroundColor: COLORS.light.primary,
    padding: 10,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  addBtnText: {
    color: "#fff",
    fontWeight: "bold",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  cancelBtn: {
    backgroundColor: "#666",
    padding: 10,
    borderRadius: 10,
    flex: 1,
    marginRight: 10,
    alignItems: "center",
  },
  cancelText: {
    color: "#fff",
    fontWeight: "bold",
  },
  applyBtn: {
    backgroundColor: COLORS.light.primary,
    padding: 10,
    borderRadius: 10,
    flex: 1,
    marginLeft: 10,
    alignItems: "center",
  },
  applyText: {
    color: "#fff",
    fontWeight: "bold",
  },
});
