import { StyleSheet } from "react-native";
import { COLORS } from "../../../core/theme/colors";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#fff" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 0.5,
    borderColor: "#ddd",
    backgroundColor: "#fff",
    justifyContent: "space-between",
  },
  headerGroup: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginLeft: 10,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
  },
  chatBg: {
    flex: 1,
    backgroundColor: "#F5FAFD",
    position: "relative",
  },
  chatTiledBg: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.12,
    zIndex: 0,
  },
  chatList: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  messageRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    marginBottom: 10,
  },
  rowLeft: { alignSelf: "flex-start" },
  rowRight: {
    alignSelf: "flex-end",
    flexDirection: "row-reverse",
  },
  pinnedMessageRow: {
    backgroundColor: "#FFFACD",
    marginHorizontal: -12,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  userAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    marginHorizontal: 6,
  },
  username: {
    fontSize: 11,
    color: "#555",
    fontWeight: "600",
    marginBottom: 2,
  },
  messageBubble: {
    maxWidth: "75%",
    padding: 10,
    borderRadius: 16,
  },
  myBubble: {
    backgroundColor: "#AECFDF",
    borderBottomRightRadius: 4,
    elevation: 0.4,
  },
  otherBubble: {
    backgroundColor: "#fff",
    borderBottomLeftRadius: 4,
    elevation: 0.4,
  },
  pinnedBubble: {
    borderWidth: 2,
    borderColor: "#FF6B6B",
  },
  pinnedLabel: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    paddingTop: 4,
  },
  pinnedText: {
    fontSize: 10,
    color: "#FF6B6B",
    fontWeight: "bold",
    marginLeft: 4,
  },
  messageText: {
    fontSize: 15,
    color: "#000",
  },
  timestamp: {
    fontSize: 11,
    color: "#888",
    alignSelf: "flex-end",
    marginTop: 4,
  },
  replyBox: {
    borderLeftWidth: 2,
    borderLeftColor: "#2FA5A9",
    backgroundColor: "#BEF3FF",
    paddingLeft: 6,
    padding: 6,
    marginBottom: 4,
    borderRadius: 4,
  },
  replyLabel: {
    fontSize: 12,
    color: "#555",
    fontWeight: "600",
  },
  replyText: {
    fontSize: 13,
    color: "#333",
  },
  replyPreview: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#BEF3FF",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#2FA5A9",
  },
  replyPreviewText: {
    color: "#444",
    fontSize: 13,
    flex: 1,
  },
  inputArea: {
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    backgroundColor: "#fff",
    borderTopWidth: 0.5,
    borderColor: "#ddd",
  },
  input: {
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "#f0f0f0",
    borderRadius: 20,
    marginHorizontal: 10,
    fontSize: 15,
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  messageMenuModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingVertical: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: "#f0f0f0",
  },
  menuText: {
    fontSize: 16,
    marginLeft: 12,
    color: "#333",
  },
});
